### ISSUE TITLE
Add GitHub Action to automatically merge ImgBot PRs

### ISSUE THREAD

**Issue by schmelto** [schmelto/NewsApp#29]
For automatically merging pull requests from ImgBot we can use following GitHub Action:

(NewsApp/.github/workflows/automerge.yml)
```
name: Merge ImgBot PRs

on: pull_request

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - name: Auto Approve
      uses: hmarr/auto-approve-action@v2.0.0
      if: github.actor == 'imgbot[bot]'
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
    - name: Merge
      uses: "pascalgn/automerge-action@v0.13.0"
      if: github.actor == 'imgbot[bot]'
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        MERGE_LABELS: ""
```

If you want you can add this action to this repo 🚀
